# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly

before_install:
  - wget https://github.com/LASzip/LASzip/archive/3.1.1.tar.gz
  - tar -xzf 3.1.1.tar.gz
  - pushd LASzip-3.1.1 && mkdir build && cd build && cmake .. && make && sudo make install && popd
  - if [[ $TRAVIS_OS_NAME == osx ]]; then export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib ; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo ldconfig ; fi

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LazIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LazIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
