# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - wget https://github.com/LASzip/LASzip/archive/3.1.1.tar.gz
  - tar -xzf 3.1.1.tar.gz
  - cd LASzip-3.1.1 && mkdir build && cd build && cmake ..
  - make
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
  - export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:$PWD/lib
  - cd ../../  # back to our git root
